<?php

namespace PhpComRapadura\CommunityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends EntityRepository
{
}
