<?php

namespace PhpComRapadura\CommunityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommunityManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityManagerRepository extends EntityRepository
{
}
